export const UPDATE_FILTERED_PRODUCTS = 'UPDATE_FILTERED_PRODUCTS';
export const UPDATE_CATEGORY_PRODUCTS = 'UPDATE_CATEGORY_PRODUCTS';
export const UPDATE_CHECKED_FILTER = 'UPDATE_CHECKED_FILTER';
export const RESET_CHECKED_FILTERS = 'RESET_CHECKED_FILTERS';
export const IS_RESULTS_PAGE = 'IS_RESULTS_PAGE';